# Generated by Django 5.2.1 on 2025-05-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_song_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year_released',
            field=models.DateField(),
        ),
    ]
