# Generated by Django 4.2.11 on 2025-04-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_album_id_alter_artist_id_alter_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.CharField(max_length=200),
        ),
    ]
